### ISSUE TITLE
templateUrl vs template

### ISSUE THREAD

**Issue by ekarlso** [preboot/angular2-webpack#29]
Whats' the pros / cons btw of template: require("../file.html") vs templateUrl: "../file.html" ?

**Comment by ocombe** [comment]
With require it will load the file at build time and bundle everything up.
With templateUrl it's loaded at runtime (and you need to have those files available).

Angular 2 is working on a "compiler" that will precompile the templates at build time so that the apps load faster, and to reduce angular 2 size (by removing the template parsers). When this is available we will add it to this starter and requiring the template will make more sense.
